# Generated by Django 2.2.16 on 2023-01-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nested_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
